### PR TITLE
Better merging of collection types

### PR DESCRIPTION
**Pull request by brutal-factories**
_This reopens the previous PR #40 , which got closed by an erroneous force-push on my part_

### CODE REVIEW

**Review by dbu — APPROVED** [review]
very cool, thanks a lot!

can you add a changelog entry that explains what the new functionality does? (and mentions that users don't need to change anything yet - apart from using PropertyTypeIterable instead of PropertyTypeArray when they extend functionality, to be forward compatible)

**Comment by dbu** [comment]
once i merged, i will merge 1.x to 2.x so that we can see only the changes for version 2.x in PR #43

**Comment by dbu** [comment]
awesome, thank you.

**Comment by dbu** [comment]
shall i tag a 1.x release for this?

**Comment by brutal-factories** [comment]
> shall i tag a 1.x release for this?

Yes, could you also bump up `liip/serializer` and `liip/serializer-jms-adapter`?

**Comment by dbu** [comment]
i will wait so we can first add the forward compatibility methods and add deprecations.

and for liip/serializer we should add the handling of generic traversable.

**Comment by dbu** [comment]
https://github.com/liip/metadata-parser/releases/tag/1.2.0

we should now upgrade liip/serializer to require parser ^1.2 and avoid the deprecations.

**Pull request merged**
